import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  IconBrandYoutube,
} from "@tabler/icons-react";

const socialLinks = [
  { link: "https://github.com/scammerpatil", icon: IconBrandGithub },
  {
    link: "https://www.linkedin.com/in/scammerpatil",
    icon: IconBrandLinkedin,
  },
  {
    link: "https://www.instagram.com/its_sauravpatil",
    icon: IconBrandInstagram,
  },
  {
    link: "https://www.youtube.com/channel/UCgG8-dXbH11vxMbImGaIRmQ",
    icon: IconBrandYoutube,
  },
  { link: "https://www.leetcode.com/u/scammerpatil", icon: IconBrandLeetcode },
];

const ExperienceInfo = [
  {
    role: "Specialist Programmer",
    company: "Infosys",
    date: "Oct 2023 - Present",
    desc: "I led software development with Spring Boot, React, and Angular, creating scalable microservices and interfaces. I optimized performance by integrating frontend and backend, and enhanced security with RESTful APIs. Collaborating in agile teams, I fostered innovation and efficiency for top-quality solutions.",
    skills: [
      "Springboot",
      "React JS",
      "Angular",
      "Node JS",
      "MySQL",
      "MongoDB",
      "Microservices",
    ],
  },
  {
    role: "System Engineer",
    company: "Infosys",
    date: "Nov 2022 - Sep 2023",
    desc: " I leveraged my skills in Java, Selenium, automation testing, and MySQL to design and implement automated testing frameworks, ensuring robust software validation. I optimized database performance and reliability, and collaborated with cross-functional teams to enhance system operations and ensure seamless integration.",
    skills: [
      "Java",
      "MySQL",
      "Hibernate",
      "Selenium",
      "Jenkins",
      "JIRA",
      "Automation Testing",
    ],
  },
];
const Slugs = [
  "java",
  "c",
  "cplusplus",
  "javascript",
  "typescript",
  "python",
  "mysql",
  "mongodb",
  "html5",
  "css3",
  "react",
  "redux",
  "nodedotjs",
  "express",
  "spring",
  "springboot",
  "nextdotjs",
  "bootstrap",
  "tailwindcss",
  "materialui",
  "chakraui",
  "daisyui",
  "tensorflow",
  "keras",
  "scikit-learn",
  "numpy",
  "pandas",
  "openai",
  "pytorch",
  "git",
  "github",
  "npm",
  "postman",
  "fastapi",
  "docker",
  "vercel",
  "jira",
  "eclipseide",
  "intellijidea",
  "androidstudio",
  "jupyter",
  "googlecloud",
  "figma",
];

export { socialLinks, ExperienceInfo, Slugs };
