export const technologies = {
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Angular",
    "Vue.js",
    "Svelte",
    "Tailwind CSS",
    "DaisyUI",
    "Bootstrap",
    "Material-UI",
    "Chakra UI",
    "Sass",
    "Less",
    "Styled Components",
    "Redux",
    "Zustand",
    "Recoil",
    "MobX",
    "Vite",
    "Webpack",
    "Parcel",
    "Flutter",
    "React Native",
    "Swift (iOS)",
    "Kotlin (Android)",
    "iOS",
    "Android",
    "PWA (Progressive Web Apps)",
    "Three.js",
    "WebGL",
    "Blazor",
  ],

  backend: [
    "Node.js",
    "Express",
    "Express JS",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "Java",
    "Spring Boot",
    "Hibernate",
    "JPA",
    "C#",
    ".NET",
    "Go",
    "Rust",
    "C++",
    "C",
    "Embedded C",
    "NestJS",
    "Ktor",
    "Gin (Go)",
    "Fiber (Go)",
    "Nodemailer",
    "EJS",
    "Pug",
    "Handlebars",
    "Mustache",
    "Jinja",
    "Liquid",
    "Razor",
    "GraphQL",
    "Apollo",
    "REST API",
    "WebSockets",
    "Socket.io",
  ],

  database: [
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Redis",
    "Oracle Database",
    "MariaDB",
    "Microsoft SQL Server",
    "Firebase Realtime Database",
    "Firestore",
    "Cassandra",
    "CouchDB",
    "Neo4j",
    "DynamoDB",
    "Elasticsearch",
  ],

  APIs: [
    "REST API",
    "GraphQL",
    "Apollo Server",
    "gRPC",
    "SOAP",
    "OpenAPI (Swagger)",
    "Postman",
    "Insomnia",
    "WebSockets",
    "Socket.io",
    "tRPC",
  ],

  hardware: [
    "Arduino",
    "Raspberry Pi",
    "ESP32",
    "ESP8266",
    "IoT",
    "Embedded Systems",
    "Microcontrollers",
    "Sensors & Actuators",
    "Robotics",
    "C",
    "C++",
    "Embedded C",
  ],

  devOps: [
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI/CD",
    "Bitbucket Pipelines",
    "Travis CI",
    "CircleCI",
    "Ansible",
    "Terraform",
    "Vagrant",
    "Prometheus",
    "Grafana",
    "Nagios",
    "New Relic",
    "ELK Stack",
    "Splunk",
    "SonarQube",
    "Nginx",
    "Apache",
    "HAProxy",
    "CI/CD",
    "Monitoring & Logging",
    "Shell Scripting",
  ],

  cloud: [
    "AWS",
    "Google Cloud Platform (GCP)",
    "Microsoft Azure",
    "Heroku",
    "Netlify",
    "Vercel",
    "DigitalOcean",
    "Cloudflare",
    "Firebase Hosting",
    "AWS Lambda",
    "S3",
    "EC2",
    "ECS",
    "EKS",
    "Azure Functions",
    "Google App Engine",
    "Cloud Run",
  ],
  mlAndAI: [
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Computer Vision",
    "Natural Language Processing (NLP)",
    "Data Science",
    "Big Data",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Scikit-Learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "OpenCV",
    "Hugging Face Transformers",
    "NLTK",
    "SpaCy",
    "Jupyter Notebook",
    "Anaconda",
    "Google Colab",
    "Tableau",
    "PowerBI",
    "Hadoop",
    "Spark",
    "Kafka",
    "Feature Engineering",
    "Model Deployment",
    "MLOps",
    "Data Visualization",
    "Time Series Analysis",
    "Reinforcement Learning",
    "Generative AI",
    "LLMs (Large Language Models)",
    "Prompt Engineering",
    "AutoML",
    "Data Cleaning",
    "Data Preprocessing",
    "Model Evaluation",
    "Hyperparameter Tuning",
  ],
};
